dataFolder = 'data/'
clickstreamFolder = dataFolder + 'clickstream/'
commonFieldFolder = dataFolder + 'commonFieldStatistics/'
valuesFolder = commonFieldFolder + 'values/'
commonFolder = dataFolder + 'common/'
specsFolder = dataFolder + 'specs/'