package util

/**
  * Created by miek on 07.12.2016.
  */

object LumberjackConstants {

  val KEY_MODULE = "module"
  val KEY_SESSION_ID = "sid"
  val KEY_USER_ID = "uid"
  val KEY_USER_ID_FROM_COOKIE = "uidc"
  val KEY_USER_ID_FOUND = "memberId"
  val KEY_MEMBER_ID = "memid"
  val KEY_PERSISTENT_COOKIE = "_c"
  val KEY_TYPE = "_t"
  val KEY_TIMESTAMP = "timestamp"

  val KEY_MODULE_NEWSESSION = "newsession"
  val KEY_MODULE_ITEM = "item"
  val KEY_MODULE_SEARCH = "search"
  val KEY_MODULE_BROWSE = "browse"
  val KEY_MODULE_PAYMENT = "payment"
  val KEY_MODULE_HOMEPAGE = "homepage"
  val KEY_MODULE_LOGIN = "login"
  val KEY_MODULE_REGISTER = "register"
  val KEY_MODULE_MAINCAT = "maincat"
  val KEY_MODULE_MAINBROWSE = "mbrowse"
  val KEY_MODULE_FOLLOW = "follow"
  val KEY_MODULE_CART = "cart"
  val KEY_MODULE_HELP = "help"
  val KEY_MODULE_LANDING = "landing"
  val KEY_MODULE_SHOPS_PAGE = "shopspage"
  val KEY_MODULE_PRIVATE_SHOPPING_BRAND = "prvbrand"

  val KEY_HELP_PAGE = "page"
  val KEY_IP = "_ip"
  val KEY_BOT = "_bot"
  val KEY_REFERER = "referer"
  val KEY_AB = "abvar"
  val KEY_GOAL = "goal"
  val KEY_GOAL_NUM = "num"
  val KEY_KEYWORD = "keyword"
  val KEY_PAGENUM = "pageNum"
  val KEY_SPEC = "spec"
  val KEY_MAX_PRICE = "maxPrice"
  val KEY_MIN_PRICE = "minPrice"
  val KEY_SELLER = "seller"
  val KEY_IS_INTERNAL = "intsrch"
  val KEY_CAT_CODE = "catCode"
  val KEY_CAT = "cat"
  val KEY_USE_DETAIL = "inDetail"
  val KEY_LOCATION = "location"
  val KEY_RECENTLY_CAME = "yni"
  val KEY_CARGO = "cargo"
  val KEY_ENDING = "btc"
  val KEY_ENDED = "btm"
  val KEY_NEW_ITEM = "newItem"
  val KEY_FORMAT = "format"
  val KEY_DUTCH = "inDutch"
  val KEY_STORE = "inStore"
  val KEY_STORE_ID = "storeId"
  val KEY_SORT = "orderBy"
  val KEY_ID = "id"
  val KEY_ID_LIST = "ids"
  val KEY_CART_ID = "cartId"
  val KEY_PAYMENT_CATEGORY = "ktgr"
  val KEY_TOTAL_FOUND = "totfound"
  var KEY_FUZZY = "fuzzy"
  val KEY_LANDING_PAGE = "landin"
  val KEY_AGENT = "agent"
  val KEY_PLATFORM = "platform"
  val KEY_DEVICE = "device"
  val KEY_CAMPAIGN_ID = "campaignId"
  val KEY_BUY_IT_NOW = "buyItNow"
  val KEY_TITLE = "title"

  val KEY_TYPE_WEB = "web"
  val KEY_TYPE_MOBILE_SITE = "msite"
  val KEY_TYPE_MOBILE_DEVICE = "mdev"
  val SHOPPING_CART_ID = "sciid"

  val SEPARATOR_FOR_PAYMENT = "\\|"
  val SEPARATOR_FOR_SEARCH_IDS = ","

}
